site_name: Kunal_Goel_SmartBridge_EPBL_AIML
theme:
  name: material
  font:
    text: Merriweather Sans
    code: Red Hat Mono
  # logo: assets/logo.png
  # favicon: assets/favicon.ico
  features:
    - navigation.tabs
    - navigations.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: deep purple
      accent: deep purple

    # # Light Mode
    # - scheme: default
    #   toggle:
    #     icon: material/weather-night
    #     name: Light mode
    #   primary: blue
    #   accent: deep orange

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
